- hosts: raspberry-pi
  remote_user: pi
  become: yes
  gather_facts: yes
  vars:
    REBOOT: yes
    UPDATE: yes
    hostname: "mochicam"
    locale: "ja_JP.UTF-8"
    timezone: "Asia/Tokyo"
    new_relic_license_key: eu01xxa713a2dfaf9f70d7ef804c97b50817NRAL
  roles:
    # - system
    # - nginx
    # - rtmp-streaming
    - new_relic
