---
- name: Update all packages
  apt:
    upgrade: dist

- name: Install necessary apt packages
  vars:
    packages:
      - ffmpeg
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ packages }}'

- name: Put a launcher
  copy:
    src: files/launch-rtmp-streamer.sh
    dest: /opt/launch-rtmp-streamer.sh
    mode: 755

- name: Put a service file
  copy:
    src: files/rtmp-streamer.service
    dest: /etc/systemd/system/rtmp-streamer.service
    mode: 755

- name: Enable this service
  systemd:
    name: rtmp-streamer
    state: started
    enabled: yes
